{% set version = '0.7.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-easystats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/easystats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/easystats/easystats_{{ version }}.tar.gz
  sha256: e6b822b725dbd2ed5a129a3fb787a6ef378562b787e4411813bb375d4c1b2522

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayestestr >=0.13.2
    - r-correlation >=0.8.4
    - r-datawizard >=0.10.0
    - r-effectsize >=0.8.6
    - r-insight >=0.19.10
    - r-modelbased >=0.8.7
    - r-parameters >=0.21.6
    - r-performance >=0.11.0
    - r-report >=0.5.8
    - r-see >=0.8.3
  run:
    - r-base
    - r-bayestestr >=0.13.2
    - r-correlation >=0.8.4
    - r-datawizard >=0.10.0
    - r-effectsize >=0.8.6
    - r-insight >=0.19.10
    - r-modelbased >=0.8.7
    - r-parameters >=0.21.6
    - r-performance >=0.11.0
    - r-report >=0.5.8
    - r-see >=0.8.3

test:
  commands:
    - $R -e "library('easystats')"           # [not win]
    - "\"%R%\" -e \"library('easystats')\""  # [win]

about:
  home: https://easystats.github.io/easystats/
  dev_url: https://github.com/easystats/easystats/
  license: MIT
  summary: A meta-package that installs and loads a set of packages from 'easystats' ecosystem
    in a single step. This collection of packages provide a unifying and consistent
    framework for statistical modeling, visualization, and reporting. Additionally,
    it provides articles targeted at instructors for teaching 'easystats', and a dashboard
    targeted at new R users for easily conducting statistical analysis by accessing
    summary results, model fit indices, and visualizations with minimal programming.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
# Type: Package

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: easystats
# Title: Framework for Easy Statistical Modeling, Visualization, and Reporting
# Version: 0.7.1
# Authors@R: c(person(given = "Daniel", family = "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206", Twitter = "@strengejacke")), person(given = "Dominique", family = "Makowski", role = "aut", email = "dom.makowski@gmail.com", comment = c(ORCID = "0000-0001-5375-9967", Twitter = "@Dom_Makowski")), person(given = "Mattan S.", family = "Ben-Shachar", role = "aut", email = "matanshm@post.bgu.ac.il", comment = c(ORCID = "0000-0002-4287-4801")), person(given = "Indrajeet", family = "Patil", role = "aut", email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531", Twitter = "@patilindrajeets")), person(given = "Brenton M.", family = "Wiernik", role = "aut", email = "brenton@wiernik.org", comment = c(ORCID = "0000-0001-9560-6336", Twitter = "@bmwiernik")), person("Etienne", "Bacher", , "etienne.bacher@protonmail.com", role = "aut", comment = c(ORCID = "0000-0002-9271-5075")), person(given = "Remi", family = "Theriault", role = "aut", email = "remi.theriault@mail.mcgill.ca", comment = c(ORCID = "0000-0003-4315-6788", Twitter = "@rempsyc")))
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: A meta-package that installs and loads a set of packages from 'easystats' ecosystem in a single step. This collection of packages provide a unifying and consistent framework for statistical modeling, visualization, and reporting. Additionally, it provides articles targeted at instructors for teaching 'easystats', and a dashboard targeted at new R users for easily conducting statistical analysis by accessing summary results, model fit indices, and visualizations with minimal programming.
# License: MIT + file LICENSE
# URL: https://easystats.github.io/easystats/
# BugReports: https://github.com/easystats/easystats/issues
# Depends: R (>= 3.6)
# Imports: bayestestR (>= 0.13.2), correlation (>= 0.8.4), datawizard (>= 0.10.0), effectsize (>= 0.8.6), insight (>= 0.19.10), modelbased (>= 0.8.7), parameters (>= 0.21.6), performance (>= 0.11.0), report (>= 0.5.8), see (>= 0.8.3), tools, utils
# Suggests: DT, flexdashboard (>= 0.6.2), jsonlite, knitr, mockery, rmarkdown, testthat (>= 3.2.1), withr, xml2
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.3.1
# Config/testthat/edition: 3
# Config/Needs/website: rstudio/bslib, r-lib/pkgdown, easystats/easystatstemplate
# NeedsCompilation: no
# Packaged: 2024-03-27 13:56:00 UTC; mail
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>, @strengejacke), Dominique Makowski [aut] (<https://orcid.org/0000-0001-5375-9967>, @Dom_Makowski), Mattan S. Ben-Shachar [aut] (<https://orcid.org/0000-0002-4287-4801>), Indrajeet Patil [aut] (<https://orcid.org/0000-0003-1995-6531>, @patilindrajeets), Brenton M. Wiernik [aut] (<https://orcid.org/0000-0001-9560-6336>, @bmwiernik), Etienne Bacher [aut] (<https://orcid.org/0000-0002-9271-5075>), Remi Theriault [aut] (<https://orcid.org/0000-0003-4315-6788>, @rempsyc)
# Repository: CRAN
# Date/Publication: 2024-03-28 08:10:02 UTC
